---
env: 'local-dev'
mixAmtEth: "0.1"
feeAmtEth: "0.001"

testing:
  mixAmtTokens: 100
  feeAmtTokens: 1

chain:
  url: "http://localhost:8545"
  chainId: 1234
  #url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  #chainId: 42
  mix:
    gasLimit: 8000000
  privateKeysPath: "../ganachePrivateKeys.json"
  deployedAddresses:
    MiMC: '0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0'
    MultipleMerkleTree: '0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da'
    Semaphore: '0x345cA3e014Aaf5dcA488057592ee47305D9B3e10'
    Mixer: '0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF'
    RelayRegistry: '0x2C2B9C9a4a25e24B174f26114e8926a9f2128FE4'

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKeyPath: "/home/di/MIXER_SECRETS/hotWalletPrivKey.json"
  broadcasterAddress: "0x627306090abaB3A6e1400e9345bC60c78a8BEf57"
  etcd:
    host: "localhost"
    port: 2379
    lockTime: 7000
  testing:
    privKeys:
      - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
      - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"

frontend:
  snarks:
    paths:
      verificationKey: 'http://localhost:8000/build/verification_key.json'
      circuit: 'http://localhost:8000/build/circuit.json'
      provingKey: 'http://localhost:8000/build/proving_key.bin'
  countdown:
    endsAtUtcMidnight: false
    endsAfterSecs: 5
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
  supportedNetworkName: "local"
  supportedNetwork: 1234
